// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddImages(arg1) {
  return window['go']['main']['App']['AddImages'](arg1);
}

export function AddTask(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function BuildGeminiRequest(arg1) {
  return window['go']['main']['App']['BuildGeminiRequest'](arg1);
}

export function BuildImagenPayload(arg1) {
  return window['go']['main']['App']['BuildImagenPayload'](arg1);
}

export function BuildPayload(arg1) {
  return window['go']['main']['App']['BuildPayload'](arg1);
}

export function CalculateChatCost(arg1, arg2) {
  return window['go']['main']['App']['CalculateChatCost'](arg1, arg2);
}

export function CalculateCost(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateCost'](arg1, arg2, arg3);
}

export function ChangeImageUI(arg1) {
  return window['go']['main']['App']['ChangeImageUI'](arg1);
}

export function CheckBatchStatus(arg1) {
  return window['go']['main']['App']['CheckBatchStatus'](arg1);
}

export function CleanupJobsFile() {
  return window['go']['main']['App']['CleanupJobsFile']();
}

export function ClearChatMemory() {
  return window['go']['main']['App']['ClearChatMemory']();
}

export function ClearFinishedJobs() {
  return window['go']['main']['App']['ClearFinishedJobs']();
}

export function ClearImages() {
  return window['go']['main']['App']['ClearImages']();
}

export function ClearTasks() {
  return window['go']['main']['App']['ClearTasks']();
}

export function CreateNewImage() {
  return window['go']['main']['App']['CreateNewImage']();
}

export function DeleteImage(arg1) {
  return window['go']['main']['App']['DeleteImage'](arg1);
}

export function DeleteSelectedImages() {
  return window['go']['main']['App']['DeleteSelectedImages']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DownloadBatchResults(arg1) {
  return window['go']['main']['App']['DownloadBatchResults'](arg1);
}

export function DuplicateTask(arg1) {
  return window['go']['main']['App']['DuplicateTask'](arg1);
}

export function GetBatchJobs() {
  return window['go']['main']['App']['GetBatchJobs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCost(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCost'](arg1, arg2, arg3);
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetImages() {
  return window['go']['main']['App']['GetImages']();
}

export function GetLastGeneratedImage(arg1) {
  return window['go']['main']['App']['GetLastGeneratedImage'](arg1);
}

export function GetModelID(arg1) {
  return window['go']['main']['App']['GetModelID'](arg1);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function HandleError(arg1, arg2) {
  return window['go']['main']['App']['HandleError'](arg1, arg2);
}

export function LoadJobs() {
  return window['go']['main']['App']['LoadJobs']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function LoadSessionUI() {
  return window['go']['main']['App']['LoadSessionUI']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function LogToFile(arg1) {
  return window['go']['main']['App']['LogToFile'](arg1);
}

export function OpenImageFolder() {
  return window['go']['main']['App']['OpenImageFolder']();
}

export function ProcessBatchItem(arg1, arg2) {
  return window['go']['main']['App']['ProcessBatchItem'](arg1, arg2);
}

export function ProcessDroppedFiles(arg1) {
  return window['go']['main']['App']['ProcessDroppedFiles'](arg1);
}

export function ProcessResponse(arg1, arg2) {
  return window['go']['main']['App']['ProcessResponse'](arg1, arg2);
}

export function RunBatch() {
  return window['go']['main']['App']['RunBatch']();
}

export function RunTask(arg1, arg2) {
  return window['go']['main']['App']['RunTask'](arg1, arg2);
}

export function RunTasks() {
  return window['go']['main']['App']['RunTasks']();
}

export function SaveBase64Image(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveBase64Image'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveSessionUI() {
  return window['go']['main']['App']['SaveSessionUI']();
}

export function SelectAndAddMultipleImages() {
  return window['go']['main']['App']['SelectAndAddMultipleImages']();
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function SubmitBatchJob(arg1) {
  return window['go']['main']['App']['SubmitBatchJob'](arg1);
}

export function TestAPI(arg1) {
  return window['go']['main']['App']['TestAPI'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function ToggleTaskDisabled(arg1) {
  return window['go']['main']['App']['ToggleTaskDisabled'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function HasGeneratedImage(arg1) {
  return window['go']['main']['App']['HasGeneratedImage'](arg1);
}

export function GetRunningTasksCount() {
  return window['go']['main']['App']['GetRunningTasksCount']();
}

export function ResetCounters() {
  return window['go']['main']['App']['ResetCounters']();
}
