// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {io} from '../models';

export function AddImages(arg1:Array<string>):Promise<void>;

export function AddTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function BuildGeminiRequest(arg1:main.TaskInfo):Promise<main.GeminiRequest>;

export function BuildImagenPayload(arg1:main.TaskInfo):Promise<Array<number>>;

export function BuildPayload(arg1:main.TaskInfo):Promise<Array<number>>;

export function CalculateCost(arg1:string,arg2:string):Promise<number>;

export function ChangeImageUI(arg1:string):Promise<void>;

export function CheckBatchStatus(arg1:main.BatchJob):Promise<void>;

export function CleanupJobsFile():Promise<void>;

export function ClearFinishedJobs():Promise<void>;

export function CreateNewImage():Promise<void>;

export function DeleteImage(arg1:string):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function DownloadBatchResults(arg1:string):Promise<void>;

export function DuplicateTask(arg1:number):Promise<void>;

export function GetBatchJobs():Promise<Array<main.BatchJob>>;

export function GetConfig():Promise<main.Config>;

export function GetCost(arg1:string,arg2:string):Promise<number>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetImages():Promise<Array<main.ImageInfo>>;

export function GetLastGeneratedImage(arg1:number):Promise<string>;

export function GetModelID(arg1:string):Promise<string>;

export function GetTasks():Promise<Array<main.TaskInfo>>;

export function HandleError(arg1:Array<number>,arg2:number):Promise<void>;

export function LoadJobs():Promise<void>;

export function LoadSession(arg1:io.Reader):Promise<void>;

export function LoadSessionUI():Promise<void>;

export function Log(arg1:string):Promise<void>;

export function LogToFile(arg1:string):Promise<void>;

export function OpenImageFolder():Promise<void>;

export function ProcessBatchItem(arg1:Array<number>,arg2:string):Promise<void>;

export function ProcessResponse(arg1:Array<number>,arg2:main.TaskInfo):Promise<void>;

export function RunBatch():Promise<void>;

export function RunTask(arg1:main.TaskInfo):Promise<void>;

export function RunTasks():Promise<void>;

export function SaveBase64Image(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveSession(arg1:io.Writer):Promise<void>;

export function SaveSessionUI():Promise<void>;

export function SelectAndAddMultipleImages():Promise<void>;

export function SubmitBatchJob(arg1:Array<main.TaskInfo>):Promise<void>;

export function TestAPI():Promise<void>;

export function TestConnection():Promise<void>;

export function ToggleTaskDisabled(arg1:number):Promise<void>;

export function UpdateTask(arg1:main.TaskInfo):Promise<void>;

export function UploadFile(arg1:Array<number>):Promise<string>;
